//! Raw FFI bindings to wolfTPM generated by bindgen.
//!
//! Use the `wolftpm` crate for safe, idiomatic Rust abstractions.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

pub mod tpm_rc;

#[cfg(feature = "swtpm")]
pub mod swtpm;
